version: "3.9"
services:
  application:
    image: tchandrahas76/accountapp:v1.4
    networks:
      - my-net
    ports: 
    - "8088:8088"
    expose:
      - 8088

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - my-net
    
volumes:
  db-data:

networks:
  my-net: 
